server:
  port: 9009
  servlet:
    context-path: /test/
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: panta-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka