server:
  port: 9001
spring:
  application:
    name: panta-zuul

zuul:
  prefix: /api
  routes:
    panta-service: /ccc/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka