server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: panta-gateway
  cloud:
    gateway:
      routes:
        - id: panta-service
          uri: lb://panta-service
          predicates:
            - Path=/api/**

        - id: panta-test
          uri: lb://panta-test
          predicates:
            - Path=/test/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka