server:
  port: 9002
  servlet:
    context-path: /api/
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: panta-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
